title: SciVizAI
description: Exploring the intersection of scientific visualization and artificial intelligence
theme: just-the-docs
name: ""

url: https://shay-saharan.github.io/SciVizAI/

aux_links:
  Feedback Form: https://shay-saharan.github.io/SciVizAI/
