title: SciVizAI
description: Exploring the intersection of scientific visualization and artificial intelligence
theme: just-the-docs
logo: "/Logo.png"
name: ""

# Expand all nav items by default
nav_expanded: false

url: https://shay-saharan.github.io/SciVizAI/

aux_links:
  Feedback Form: https://shay-saharan.github.io/SciVizAI/
