title: SciVizAI
description: Exploring the intersection of scientific visualization and artificial intelligence
theme: just-the-docs
name: ""

url: https://shehryar.github.io/SciVizAI

aux_links:
  Feedback Form: https://shehryar.github.io/SciVizAI
